### ISSUE TITLE
module should not write entire FASTA to file unless debug mode

### ISSUE THREAD

**Issue by ArtPoon** [tnguyencfe/SlidingWindowTrees#1]
This makes the module too slow because every window has to process the entire file.  This is massively redundant.  We should never even have to store an explicit representation of the FASTA-structured alignment in memory or as a file.  I'm going to have a crack at modifying this code.

**Comment by tnguyencfe** [comment]
Fixed by f73c02231af29afb1999193b3928c5247cef94d5
